apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: insightforge
data:
  #Database
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "insightforge"
  DATABASE_USER: "postgres"

  # Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  
  # Pinecone
  PINECONE_ENVIRONMENT: "us-west1-gcp"
  PINECONE_INDEX_NAME: "insightforge-context"
  
  # Python
  PYTHONUNBUFFERED: "1"

